[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
capsulex_program = "J1r7tHjxEuCcSYVrikUKxzyeeccuC3QbyHjUbY8Pw7uH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test-game = "anchor build && anchor deploy && pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/game-tests.ts"
test-semantic = "anchor build && anchor deploy && pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/semantic-integration-tests.ts"
test-capsulex = "anchor build && anchor deploy && pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/capsulex-program.ts"

# This is a test for the semantic integration test specifically "Accepts semantically equivalent answers" test
test-specific = "anchor build && anchor deploy && pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/semantic-integration-tests.ts --grep 'Accepts semantically equivalent answers'"
